import com.redhat.demos.model.Person;
import com.redhat.demos.model.DecisionResponse;

rule "Person is an Adult"
when
    $p: Person(age >= 18)
then
    System.out.println("Rule " + drools.getRule().getName() + " fired!");
    insert(new DecisionResponse(true));
end

rule "Person is not Adult"
when
    $p: Person(age <= 18)
then
    System.out.println("Rule " + drools.getRule().getName() + " fired!");
    insert(new DecisionResponse(false));
end